# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('APid', models.CharField(max_length=200)),
                ('description1', models.CharField(max_length=200)),
                ('description2', models.CharField(max_length=200)),
                ('description3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='APReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('selectionReason', models.CharField(max_length=200)),
                ('atPat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.AP')),
            ],
        ),
    ]
